### ISSUE TITLE
Combined log-info and log-warn output?

### ISSUE THREAD

**Issue by bosschaert** [alexparvulescu/thelogist#1]
Is it possible to generate a single output file that contains both the log-info.txt and log-warn.txt contents, and log messages on any other level? This would still obey the rules in the configuration file re ignoring etc...

**Comment by alexparvulescu** [comment]
@bosschaert I finally got around to implementing this, sorry for the delay. if you are still interested, you should find the 0.0.2 release available under the releases tab

**Comment by bosschaert** [comment]
Fantastic, thanks @alexparvulescu ! I'll most likely use this project for an assignment that I have to work on in the coming few weeks!
